language: python

os:
  - linux
  - osx

python:
  - "2.7.16"
  - "3.6.7"
  
cache: pip

before_install:
  - python --version
  - pip install -U pip
  
install:
  - pip install -r requirements.txt

script:
  - python DigitalEpidemiology.py
