language: python

jobs:
  include:
    - os: linux
      python: 2.7
      env: TOXENV=py27
    - os: osx
      language: generic
      env: TOXENV=py27

cache: pip

before_install:
  - python --version
  - pip install -U pip
  
install:
  - pip install -r requirements.txt

script:
  - python DigitalEpidemiology.py
